src/histolab/slide.py
src/tests/unit/test_slide.py

Remove `scale_factor` from the attributes of Slide. 
Closes #4

Remove scale_factor from the attributes of Slide

---

tests/unit/test_slide.py

This PR will include a bunch of commits with other unit test cases

Tests improvement

---

src/histolab/slide.py
src/histolab/tiles.py
src/histolab/util.py
tests/fixtures/__init__.py
tests/unit/test_util.py

This PR includes:
- refactoring of lazy responders for test fixtures loaders
- cache mechanism for property using a @lazyproperty

Caching properties for `Slide`

---

.coveragerc
setup.py

This PR exclude an olde file from coverage. This file should be deleted asap

Exclude tiles from coverage

---

src/histolab/data/__init__.py
src/histolab/data/_registry.py

Add 3 diagnostic slides with pen markers.
Addresses issue #60

Add TCGA breast diagnostic slides

---

.travis.yml
src/histolab/slide.py
tests/unit/test_slide.py
tests/unitutil.py

New method `show` in `Slide` that displays the slide thumbnail if available

Add show method for displaying its thumbnail

---

src/histolab/slide.py
tests/unit/test_slide.py

- add dunder method __repr__ to slide
- add unit test for slide scale factor

Address issues

---

src/histolab/slide.py
src/histolab/tile.py
src/histolab/tiler.py
src/histolab/util.py
tests/unit/test_slide.py
tests/unit/test_tiler.py
tests/unitutil.py

At the moment the extraction at level 0 is really slow (due to the size of the tissue mask I suppose, maybe we can think to optimize somehow later).

Add Tiler module with RandomTiler

---

src/histolab/filters/image_filters_functional.py

Get rid of skimage future warning 1

---

src/histolab/filters/image_filters_functional.py

Get rid of skimage future warning 2

---

docs/conf.py
docs/index.rst
requirements-dev.txt
src/histolab/data/__init__.py
src/histolab/data/_registry.py
src/histolab/slide.py
tests/unit/test_slide.py

- fix issue https://github.com/MPBA/histolab/issues/80
- add missing docstrings and unit test
- add quickstart to docs
- embedding latex formulas in docs

Quickstart docs

---

docs/index.rst
docs/quickstart.rst
docs/readme.rst

fix docs setuptools

---

docs/api/tiler.rst
setup.py
src/histolab/slide.py
src/histolab/tiler.py
src/histolab/util.py
tests/unit/test_slide.py
tests/unit/test_tiler.py
tests/unit/test_util.py

Add Grid tiler

---

tests/unit/data/test_data.py
tests/unit/filters/test_image_filters.py
tests/unit/filters/test_morphological_fillters.py

New tests for data and morphological filters

Increase coverage

---

src/histolab/filters/image_filters.py
src/histolab/filters/image_filters_functional.py
src/histolab/tile.py
tests/base.py
tests/unit/test_util.py

Grey -> Gray

---

src/histolab/filters/image_filters.py
tests/unit/filters/test_image_filters.py

Add Lambda filter

---

src/histolab/slide.py
src/histolab/tiler.py
tests/unit/test_tiler.py

Save tiles in slide's processed_path

---

setup.py
src/histolab/tiler.py
tests/unit/test_tiler.py

Pandas has been removed in favor of using std lib for saving csv in `save_report` function
linked issue: #130

Remove pandas dependency

---

.flake8
.travis.yml
src/histolab/tiler.py
tests/integration/test_morphological_filters.py
tests/unit/test_slide.py
tests/unit/test_tiler.py

There are failing tests on Windows, needed to be fixed later
EDIT: all the tests are passing now

Travis build on macOS and Windows

---

.flake8
.travis.yml
setup.cfg
src/histolab/data/__init__.py
src/histolab/filters/image_filters_functional.py
src/histolab/slide.py
src/histolab/tile.py
src/histolab/tiler.py
src/histolab/util.py
tests/unit/test_slide.py

Cleaning stuff and ordering properties. Just an style exercise PR :D

Grooming and cleaning stuff

---

src/histolab/data/__init__.py
src/histolab/data/_registry.py
src/histolab/exceptions.py
src/histolab/filters/compositions.py
src/histolab/filters/image_filters.py
src/histolab/filters/morphological_filters.py
src/histolab/scorer.py
src/histolab/slide.py
src/histolab/tiler.py
src/histolab/util.py
tests/fixtures/__init__.py
tests/integration/test_scorer.py
tests/integration/test_slide.py
tests/integration/test_tile.py
tests/unit/filters/test_image_filters.py
tests/unit/filters/test_morphological_fillters.py
tests/unit/test_exceptions.py
tests/unit/test_scorer.py
tests/unit/test_slide.py
tests/unit/test_tile.py
tests/unit/test_tiler.py
tests/unit/test_util.py

This PR fixes some violation for best practice rules:
e.g. snake_case names, uppercase constant, pointless object in class declaration, etc...

Refactoring class declaration py3

---

docs/conf.py
setup.py

openslide-python returns

---

src/histolab/exceptions.py
src/histolab/scorer.py
src/histolab/tile.py
src/histolab/tiler.py
src/histolab/types.py
src/histolab/util.py
tests/integration/test_tile.py
tests/unit/filters/test_image_filters.py
tests/unit/filters/test_morphological_fillters.py
tests/unit/test_compositions.py
tests/unit/test_scorer.py
tests/unit/test_slide.py
tests/unit/test_tile.py
tests/unit/test_tiler.py
tests/unit/test_util.py
tests/unitutil.py

- fix some odd test assertions
- clean names and fixtures
- add missing main comments in module

Grooming and cleaning pt3

---

tests/benchmarks/test_benchmarks.py

add benchmarks for:
- `np_to_pil`
- `apply_mask_image`

new tests in benchmarks

---

.travis.yml
src/histolab/exceptions.py
src/histolab/slide.py
src/histolab/tiler.py
src/histolab/util.py
tests/unit/test_tiler.py
tests/unit/test_util.py

Lazyproperty decorator refactoring using builtin `functools` lib
Linked issue : https://github.com/histolab/histolab/issues/159

Refactor py2 lazyproperty

---

src/histolab/slide.py
src/histolab/tiler.py
src/histolab/util.py
tests/unit/test_slide.py
tests/unit/test_tiler.py

Fixes and tweaks

---

examples/GTEx/README.md
examples/GTEx/extract_tile_pw_gtex.py
examples/TCGA/README.md
examples/TCGA/extract_tile_pw_tcga.py
examples/examples_reqs.txt

This PR includes minor changes to the examples, including:
- small fixes to CLI default params, error handling, and overall execution progress messages.
- new files of requirements to be installed (with instructions)
- some rephrasing in README (tcga)
Mirror of the previous PR - hopefully with more luck this time 😇

Examples Fix and Refactoring (round 2)

---

src/histolab/filters/image_filters.py
src/histolab/filters/image_filters_functional.py
tests/integration/test_image_filters.py
tests/unit/filters/test_image_filters.py

fix issue #117

---

README.md
docs/quickstart.rst
src/histolab/tiler.py
tests/integration/test_tiler.py
tests/unit/test_tiler.py

Tilers control tissue_percent parameter of has_enough_tissue

---

src/histolab/slide.py
src/histolab/tiler.py
tests/integration/test_tiler.py
tests/unit/test_slide.py
tests/unit/test_tiler.py

This PR allow to specify negative level values for all the Tilers #169

enable negative indexing for slide.level

---

src/histolab/filters/image_filters.py
src/histolab/filters/morphological_filters.py
src/histolab/tile.py
tests/unit/test_tile.py

Implement Filter protocol

---

docs/quickstart.rst

resolve issue [#217]( https://github.com/histolab/histolab/issues/217)

fix quickstart bug

---

requirements-dev.txt
src/histolab/slide.py
tests/unit/test_slide.py
tests/unit/test_tiler.py

Allow pathlib.Path as Slide path paramerer

---

src/histolab/tiler.py
tests/unit/test_tiler.py

add logger in tiler

---

src/histolab/filters/image_filters.py
src/histolab/filters/image_filters_functional.py
src/histolab/util.py

here the reason: https://docs.python.org/3/library/operator.html#operator.lt

change Callable[..., bool] to Callable[..., Any]

---

src/histolab/slide.py
src/histolab/tiler.py
tests/integration/test_tiler.py
tests/unit/test_tiler.py

Extract random tiles now respect the given tile size

---

.github/workflows/tests.yml
src/histolab/filters/image_filters.py

New step in the CI that runs the doctest modules.
FYI: one test in the doctests has been fixed due to an error (image must be 2D)

doctests in CI

---

docs/conf.py

Put type hints in description and not in signature

---

.github/workflows/benchmarks.yml
.github/workflows/tests.yml
.pre-commit-config.yaml
tests/unit/data/test_data.py

- Black step in github actions CI

Add black in CI

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Fixes: https://github.com/histolab/histolab/issues/282

Add PR template, fix CONTRIBUTING page

---

.github/PULL_REQUEST_TEMPLATE.md

Link automatically issues in PR template

---

.github/ISSUE_TEMPLATE/bug_report.md

Include histolab version in issue template
* Fixes:

Include histolab version in issue template

---

.github/workflows/tests.yml
.pre-commit-config.yaml
README.md
bandit.yaml
requirements-dev.txt

Add bandit hook in pre commit and CI (for reference https://github.com/PyCQA/bandit)
* Fixes:

Add security linter with Bandit in pre commit and CI

---

docs/installation.rst
docs/quickstart.rst
docs/tissue_masks.rst

Fix docs links in tissue_mask

---

src/histolab/scorer.py
tests/integration/test_scorer.py

add cellularity score

---

.github/workflows/tests.yml
README.md
docs/quickstart.rst
src/histolab/exceptions.py
src/histolab/slide.py
tests/integration/test_slide.py
tests/unit/test_slide.py

add conversion level - magnification factor, when possible

---

examples/TCGA/README.md
examples/TCGA/extract_tile_pw_tcga.py

Add warning in the TCGA example to inform the unavailability of TCGA data portal

add warning in readme

---

docs/requirements.txt

Upgrade sphinx to 4.2.0 to fix incompatibility with docutils 0.18
* Fixes: #338

Upgrade sphinx to 4.2.0 to fix incompatibility with docutils 0.18

---

docs/api/filters.rst
docs/requirements.txt
histolab/filters/image_filters.py
histolab/filters/image_filters_functional.py
tests/integration/test_image_filters.py

Conversion from RGB to HSV preserves HSV color space range

---

.github/workflows/benchmarks.yml

Use Python 3.9 for benchmarks

---

.github/workflows/tests.yml
README.md
docs/contributing.rst
setup.py

add python3.10 jobs in ci

---

histolab/slide.py
tests/unit/test_slide.py

Allow only keeping a subset of slides for SlideSet. This would be useful when, for example, you want to exclude slides used in machine learning model training for cross validation.
* Fixes:

Allow only keeping a subset of slides for SlideSet

---

docs/index.rst
docs/readme.rst

Fix link to installation instructions

---

histolab/slide.py
tests/unit/test_slide.py

Fix SlideSet not passing along args to Slide

---

histolab/tile.py
tests/unit/test_tile.py

None as default value for `level` for `Tile`, instead of 0
* Fixes:

None as default level for Tile, instead of 0

---

setup.py

Specify large_image version to last working version

---

.github/workflows/tests.yml
.pre-commit-config.yaml
histolab/slide.py

Update black to fix issue with broken click dependency.
See https://github.com/psf/black/issues/2964
* Fixes:

Fix black dependency issue

---

docs/tissue_masks.rst
histolab/masks.py
tests/unit/test_masks.py

Co-authored-by: ernestoarbitrio <ernesto.arbitrio@gmail.com>
Allow custom filters in BiggestTissueBoxMask. Follow-up of #377
* Fixes:

Allow custom filters in BiggestTissueBoxMask

---

requirements.txt
tests/integration/test_slide.py

Allow openslide-python 1.2.0
* Fixes:

Allow openslide-python 1.2.0

---

CONTRIBUTING.md

Update Contributing guidelines after poetry migration

---

.github/workflows/tests.yml
docs/requirements.txt
readthedocs.yml

Followed the instruction here https://docs.readthedocs.io/en/stable/guides/poetry.html
* Fixes:

fix read the docs build

---

.github/workflows/tests.yml
.pre-commit-config.yaml
poetry.lock

fix cache id reference in tests.yml

---

histolab/slide.py

Fix typo in doc of thumbnail size

---

docs/api/stain_normalizer.rst

Update documentation with stain normalization methods (Macenko and Reinhard)
* Fixes:

add intro and example of stain norm docs

---

.github/workflows/tests.yml
readthedocs.yml

Fix readthedocs docs building

---

.github/workflows/tests.yml
.pre-commit-config.yaml
CONTRIBUTING.md
README.md
docs/contributing.rst
poetry.lock
pyproject.toml

Drop support for Python 3.8

---

.github/workflows/tests.yml

coverage fix
